dist: xenial
language: python
env:
  global:
    - secure: "vJ6ISg78UUTBzNwc44bsf+VGciI9fKqnrThYGEDPiSSIbzG5Il1YCv7aSaNAsOf/QpaSbSlO8iNpkNVZ2o6P0zy4CLdiYAyBzmNm5QTaXcRKmF9sAVK7hPSt9Z5KhBQbpSxlrzxO46KwRh8ux9BIXXy07mHo9pz88dEOhMS4egiHahDCa/AzraupsJ9CaTJAnz8O6IWLM71l6cbqkyUldxNY3oO7QQ4Y0iyS/XaMzvB8znQKWOnH8ylz/HGLltd2Mk681vIHL4QQEpa4wZKucv/BfNUq6yxjwOXEV0UB7JasN3e7Cocw9Wyd7whImwY3ygBTM5nbx9tlI4OrZ83UURGAIJqe4Bx3HM6EPSYMZKAkiZsqt8AXKJRD4q/knK5l6qGbpEx5aKPYpGOEvQxPFl4CQn9OSsKjW5jw655bFVFO317U+jVB3X5QS3/rleMDdiwfC9FcYuquwcl7lSYAC6kA/9nEIRi4VIm7UWKwb8uBDdkuqeJQsZG3oQdgf0C9dLmerloQMLGl+DS/epeiiQgHnYyPHANQSCOa443ZTSqutdZVecFmALvJhgftdJtyV7IbLpFJYec4p6ofvU9pARAkDs35XCGEXw7ZmX1TsgjlOKH1NCZUwrH7zyPONA2mF+ptjDw502ckZdnecizHqeYkFnlNyz4WgqPNhAVq/S4="
matrix:
  include:
    - name: Python 3.6 Tests
      python: "3.6"
      env: POSARGS="" TOXENV="py36"
    - name: Python 3.7 Tests
      python: "3.7"
      env: POSARGS="" TOXENV="py37"
    - name: Documentation
      python: "3.7"
      env: DOCS="true"
install:
  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
  - travis_wait source .travis/texlive/texlive_install.sh
  - pip install tox
  - pip install codecov
  - pip freeze
  - printenv
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
script:
  - set -e
  - |
    if [[ "${DOCS}" == "true" ]]; then
      source .travis/docs.sh
    else
      tox -e $TOXENV -- $POSARGS
    fi
  - echo "DONE"
after_success:
  - if [[ "${DOCS}" != "true" ]]; then codecov; fi
