"""The active configuration, and loading of `bibdeskparser.toml`.

This module defines the {class}`Config` class and its single instance
{data}`active`, the process-global configuration: the
`verify_types`/`verify_fields` validation flags, the effective
entry-type/field tables (the built-in data model from
`bibdeskparser.entrytypes`, possibly extended or replaced by a config
file), the `auto_key` settings for autogenerated citation keys
(used by {meth}`~bibdeskparser.Library.rekey`), and the `auto_file`
settings for autogenerated attachment file names (used by
{meth}`~bibdeskparser.Library.add_file` and
{meth}`~bibdeskparser.Library.rename_file`). The configuration is
process-global because entry-type and field validation happens on
individual {class}`~bibdeskparser.Entry` objects, which hold no
reference to any owning library.

{data}`active` is exposed publicly as the `Library.config` class
attribute. A `bibdeskparser.toml` file replicates some of the
preferences the BibDesk application offers; see the
[configuration](configuration) reference page for the file format and
discovery rules.
"""

import os
import warnings
from pathlib import Path

from . import entrytypes, specifiers
from .macros import is_valid_macro_name, normalize_macro_name

try:
    import tomllib  # Python 3.11+
except ModuleNotFoundError:  # pragma: no cover - Python 3.10
    import tomli as tomllib

__all__ = []

# All members whose name does not start with an underscore must be listed
# either in __all__ or in __private__
__private__ = [
    "CONFIG_FILENAME",
    "CONFIG_ENV_VAR",
    "discover",
    "AutoKey",
    "AutoFile",
    "AddAbstract",
    "AddPreprint",
    "Config",
    "active",
]

#: The name of the configuration file that is searched for.
CONFIG_FILENAME = "bibdeskparser.toml"

#: The environment variable naming the user-level configuration file,
#: replacing the XDG location.
CONFIG_ENV_VAR = "BIBDESKPARSER_CONFIG"

# The recognized top-level keys of a `bibdeskparser.toml`; anything else
# triggers a (non-fatal) warning, for forward compatibility.
_KNOWN_TOP_LEVEL_KEYS = frozenset(
    (
        "verify_types",
        "verify_fields",
        "types",
        "fields",
        "default_bib_file",
        "auto_key",
        "auto_file",
        "add_abstract",
        "add_preprint",
        "initials",
        "journal_macros",
        "protected_words",
    )
)


def _xdg_config_path():
    """The XDG standard location of `bibdeskparser.toml` (a `Path`).

    This is `$XDG_CONFIG_HOME/bibdeskparser/bibdeskparser.toml`, falling
    back to `~/.config/bibdeskparser/bibdeskparser.toml` when
    `$XDG_CONFIG_HOME` is unset.
    """
    base = os.environ.get("XDG_CONFIG_HOME") or (Path.home() / ".config")
    return Path(base) / "bibdeskparser" / CONFIG_FILENAME


def discover(bib_dir=None, config_file=None):
    """Locate the applicable `bibdeskparser.toml`, first found wins.

    The locations are searched in order of precedence:

    1. `config_file`, if given (the `Library.config.config_file`
       override); raises {exc}`FileNotFoundError` if it does not exist.
    2. `CONFIG_FILENAME` in `bib_dir` (the directory of the `.bib` file,
       or the current working directory if `bib_dir` is `None`).
    3. The file named by the `BIBDESKPARSER_CONFIG` environment
       variable, if the variable is set; raises
       {exc}`FileNotFoundError` if it does not exist. An empty value
       disables the user-level location entirely (no error).
    4. `CONFIG_FILENAME` in the XDG location (see `_xdg_config_path`),
       only when `BIBDESKPARSER_CONFIG` is unset.

    Returns the `Path` of the first existing file, or `None` if none of
    the locations has one.
    """
    if config_file is not None:
        path = Path(config_file)
        if not path.exists():
            raise FileNotFoundError(
                f"config_file does not exist: {config_file}"
            )
        return path
    local = Path(bib_dir or Path.cwd()) / CONFIG_FILENAME
    if local.exists():
        return local
    env = os.environ.get(CONFIG_ENV_VAR)
    if env is not None:
        # Unlike $XDG_CONFIG_HOME (where empty means "unset", per the
        # XDG spec), an explicitly empty value is meaningful here: no
        # user-level config at all.
        if not env:
            return None
        path = Path(env)
        if not path.exists():
            raise FileNotFoundError(f"${CONFIG_ENV_VAR} does not exist: {env}")
        return path
    xdg = _xdg_config_path()
    if xdg.exists():
        return xdg
    return None


# -- stateless parsing helpers ---------------------------------------- #


def _parse(path):
    """Parse the TOML file at `path`, raising a {exc}`ValueError` (that
    names the file) if it is malformed."""
    try:
        with open(path, "rb") as toml_file:
            return tomllib.load(toml_file)
    except tomllib.TOMLDecodeError as exc:
        raise ValueError(f"invalid config file {path}: {exc}") from exc


def _bool(raw, key):
    """Read boolean `key` from `raw`, defaulting to `True`."""
    value = raw.get(key, True)
    if not isinstance(value, bool):
        raise ValueError(f"{key} must be a boolean, not {type(value)!r}")
    return value


def _field_list(value, context):
    """Validate `value` as a list of field-name strings; return them
    lowercased."""
    if not isinstance(value, list) or not all(
        isinstance(field, str) for field in value
    ):
        raise ValueError(f"{context} must be a list of strings")
    return [field.lower() for field in value]


def _build(raw):
    """Build the entry-type/field attribute values for {class}`Config`
    from a parsed `bibdeskparser.toml` (`raw`), layering its
    customizations onto the built-in defaults."""
    unknown = set(raw) - _KNOWN_TOP_LEVEL_KEYS
    if unknown:
        warnings.warn(
            f"unknown key(s) in {CONFIG_FILENAME}: {sorted(unknown)}",
            UserWarning,
            stacklevel=4,
        )

    documented_types = {
        entry_type: {
            "required": tuple(spec["required"]),
            "optional": tuple(spec["optional"]),
        }
        for entry_type, spec in entrytypes.DOCUMENTED_TYPES.items()
    }
    recognized = set(entrytypes.RECOGNIZED_ENTRY_TYPES)
    universal = set(entrytypes.UNIVERSAL_FIELDS)
    known = set(entrytypes.KNOWN_FIELDS)

    types_table = raw.get("types", {})
    if not isinstance(types_table, dict):
        raise ValueError("[types] must be a table")
    for name, spec in types_table.items():
        if not isinstance(spec, dict):
            raise ValueError(f"[types.{name}] must be a table")
        name = name.lower()
        required = _field_list(
            spec.get("required", []), f"[types.{name}] required"
        )
        optional = _field_list(
            spec.get("optional", []), f"[types.{name}] optional"
        )
        replace = bool(spec.get("replace", False))
        if replace or name not in documented_types:
            documented_types[name] = {
                "required": tuple(required),
                "optional": tuple(optional),
            }
        else:
            base = documented_types[name]
            documented_types[name] = {
                "required": base["required"]
                + tuple(f for f in required if f not in base["required"]),
                "optional": base["optional"]
                + tuple(f for f in optional if f not in base["optional"]),
            }
        recognized.add(name)
        known.update(required)
        known.update(optional)

    fields_table = raw.get("fields", {})
    if not isinstance(fields_table, dict):
        raise ValueError("[fields] must be a table")
    extra_universal = _field_list(
        fields_table.get("universal", []), "[fields] universal"
    )
    universal.update(extra_universal)
    known.update(extra_universal)
    known.update(_field_list(fields_table.get("known", []), "[fields] known"))

    return {
        "verify_types": _bool(raw, "verify_types"),
        "verify_fields": _bool(raw, "verify_fields"),
        "documented_types": documented_types,
        "recognized_entry_types": recognized,
        "universal_fields": universal,
        "known_fields": known,
    }


def _parse_default_bib_file(raw):
    """Read the optional `default_bib_file` key from `raw`.

    Returns a `Path` with environment variables (`$VAR`) and a leading
    `~` expanded, or `None` if the key is absent.
    """
    value = raw.get("default_bib_file", None)
    if value is None:
        return None
    if not isinstance(value, str):
        raise ValueError(
            f"default_bib_file must be a string, not {type(value)!r}"
        )
    return Path(os.path.expandvars(value)).expanduser()


def _normalize_format_spec(value, context="key"):
    """Validate and normalize an auto-key or auto-file `format_spec`.

    `value` is either a single format string (applied to every entry
    type) or a per-type `dict` mapping entry-type names to format
    strings, with the empty string `""` as the fallback for
    unlisted types. Every format string is compiled (in `context`) to
    validate it, so a malformed one raises {exc}`ValueError` (or
    {exc}`NotImplementedError`, for `%i`). Returns the spec with the
    `dict` keys stripped and lowercased (a `str` is returned as is)."""
    label = "auto-file" if context == "file" else "auto-key"
    if isinstance(value, str):
        specifiers.compile_format(value, context=context)  # validate
        return value
    if isinstance(value, dict):
        if not value:
            raise ValueError(f"{label} format_spec table must not be empty")
        normalized = {}
        for entry_type, format_string in value.items():
            if not isinstance(entry_type, str):
                raise ValueError(
                    f"{label} format_spec keys must be entry-type names, "
                    f"not {type(entry_type)!r}"
                )
            if not isinstance(format_string, str):
                raise ValueError(
                    f"{label} format_spec values must be format strings, "
                    f"not {type(format_string)!r}"
                )
            specifiers.compile_format(format_string, context=context)
            normalized[entry_type.strip().lower()] = format_string
        return normalized
    raise ValueError(
        f"{label} format_spec must be a format string or a table "
        "mapping entry-type names (with '' as the fallback) to format "
        f"strings, not {type(value)!r}"
    )


class AutoKey:
    """The `[auto_key]` settings for autogenerated citation keys,
    exposed as `Library.config.auto_key`.

    Attributes:

    * `format_spec` (default `None`): the auto-key format -- a single
      format string in BibDesk's
      [format-specifier language](format-specifiers), or a per-type
      `dict` mapping entry-type names (with `""` as the fallback) to
      format strings. Assigning it validates every format string in it
      (raising {exc}`ValueError` for a malformed one) and lowercases
      the `dict` keys.
    * `lowercase` (default `False`): whether to lowercase the whole
      generated key.
    * `clean` (default `"tex"`): how much TeX markup to strip from
      field values -- one of `"none"`, `"braces"`, or `"tex"`.
    """

    def __init__(self):
        self._format_spec = None
        self.lowercase = False
        self._clean = "tex"

    @property
    def format_spec(self):
        """The auto-key format (see the class docstring)."""
        return self._format_spec

    @format_spec.setter
    def format_spec(self, value):
        self._format_spec = (
            None if value is None else _normalize_format_spec(value)
        )

    @property
    def clean(self):
        """The TeX-cleanup level (see the class docstring)."""
        return self._clean

    @clean.setter
    def clean(self, value):
        if value not in ("none", "braces", "tex"):
            raise ValueError(
                "auto_key clean must be one of 'none', 'braces', 'tex', "
                f"not {value!r}"
            )
        self._clean = value

    def __repr__(self):
        return (
            f"AutoKey(format_spec={self._format_spec!r}, "
            f"lowercase={self.lowercase!r}, clean={self._clean!r})"
        )


def _parse_auto_key(raw):
    """Read the optional `[auto_key]` table from `raw`.

    Returns an {class}`AutoKey` (holding the built-in defaults if the
    table is absent). `format_spec` and `clean` are validated by
    `AutoKey`'s own setters."""
    auto_key = AutoKey()
    table = raw.get("auto_key", None)
    if table is None:
        return auto_key
    if not isinstance(table, dict):
        raise ValueError("[auto_key] must be a table")
    unknown = set(table) - {"format_spec", "lowercase", "clean"}
    if unknown:
        warnings.warn(
            f"unknown key(s) in [auto_key]: {sorted(unknown)}",
            UserWarning,
            stacklevel=5,
        )
    if "format_spec" not in table:
        raise ValueError(
            "[auto_key] must contain a 'format_spec', e.g. "
            'format_spec = "%a1%Y%u0"'
        )
    auto_key.format_spec = table["format_spec"]
    lowercase = table.get("lowercase", False)
    if not isinstance(lowercase, bool):
        raise ValueError(
            "[auto_key] lowercase must be a boolean, "
            f"not {type(lowercase)!r}"
        )
    auto_key.lowercase = lowercase
    auto_key.clean = table.get("clean", "tex")
    return auto_key


class AutoFile:
    """The `[auto_file]` settings for autogenerated attachment file
    names, exposed as `Library.config.auto_file`.

    Attributes:

    * `format_spec` (default `None`): the auto-file format -- a single
      format string in BibDesk's
      [format-specifier language](format-specifiers) (file-name
      dialect, e.g. `"%f{Cite Key}%u0%e"`), or a per-type `dict`
      mapping entry-type names (with `""` as the fallback) to format
      strings. Assigning it validates every format string in it
      (raising {exc}`ValueError` for a malformed one, including one
      without the required `%u`/`%U`/`%n` unique specifier) and
      lowercases the `dict` keys.
    * `location` (default `Path(".")`): where auto-filed attachments
      go -- a directory path, relative to the `.bib` file's directory
      or absolute, with `~` and `$VAR` expanded on assignment. Must
      not be empty.
    * `lowercase` (default `False`): whether to lowercase the whole
      generated file name.
    * `clean` (default `"tex"`): how much TeX markup to strip from
      field values -- one of `"none"`, `"braces"`, or `"tex"`.
    * `file_automatically` (default `False`): whether
      {meth}`~bibdeskparser.Library.add_file` auto-files new
      attachments by default (the equivalent of BibDesk's *File
      papers into the papers folder automatically* preference).
    """

    def __init__(self):
        self._format_spec = None
        self._location = Path(".")
        self.lowercase = False
        self._clean = "tex"
        self.file_automatically = False

    @property
    def format_spec(self):
        """The auto-file format (see the class docstring)."""
        return self._format_spec

    @format_spec.setter
    def format_spec(self, value):
        self._format_spec = (
            None
            if value is None
            else _normalize_format_spec(value, context="file")
        )

    @property
    def location(self):
        """The auto-file location (see the class docstring)."""
        return self._location

    @location.setter
    def location(self, value):
        if not isinstance(value, (str, Path)):
            raise ValueError(
                f"auto_file location must be a path, not {type(value)!r}"
            )
        if not str(value):
            raise ValueError("auto_file location must not be empty")
        self._location = Path(os.path.expandvars(str(value))).expanduser()

    @property
    def clean(self):
        """The TeX-cleanup level (see the class docstring)."""
        return self._clean

    @clean.setter
    def clean(self, value):
        if value not in ("none", "braces", "tex"):
            raise ValueError(
                "auto_file clean must be one of 'none', 'braces', 'tex', "
                f"not {value!r}"
            )
        self._clean = value

    def __repr__(self):
        return (
            f"AutoFile(format_spec={self._format_spec!r}, "
            f"location={str(self._location)!r}, "
            f"lowercase={self.lowercase!r}, clean={self._clean!r}, "
            f"file_automatically={self.file_automatically!r})"
        )


def _parse_auto_file(raw):
    """Read the optional `[auto_file]` table from `raw`.

    Returns an {class}`AutoFile` (holding the built-in defaults if the
    table is absent). `format_spec`, `location`, and `clean` are
    validated by `AutoFile`'s own setters."""
    auto_file = AutoFile()
    table = raw.get("auto_file", None)
    if table is None:
        return auto_file
    if not isinstance(table, dict):
        raise ValueError("[auto_file] must be a table")
    known = {
        "format_spec",
        "location",
        "lowercase",
        "clean",
        "file_automatically",
    }
    unknown = set(table) - known
    if unknown:
        warnings.warn(
            f"unknown key(s) in [auto_file]: {sorted(unknown)}",
            UserWarning,
            stacklevel=5,
        )
    if "format_spec" not in table:
        raise ValueError(
            "[auto_file] must contain a 'format_spec', e.g. "
            'format_spec = "%f{Cite Key}%u0%e"'
        )
    auto_file.format_spec = table["format_spec"]
    auto_file.location = table.get("location", ".")
    for key in ("lowercase", "file_automatically"):
        value = table.get(key, False)
        if not isinstance(value, bool):
            raise ValueError(
                f"[auto_file] {key} must be a boolean, not {type(value)!r}"
            )
        setattr(auto_file, key, value)
    auto_file.clean = table.get("clean", "tex")
    return auto_file


class AddAbstract:
    """The `[add_abstract]` settings -- the defaults for the keyword
    arguments of {meth}`~bibdeskparser.Library.add_abstract` --
    exposed as `Library.config.add_abstract`.

    Attributes:

    * `min_confidence` (default `"high"`): the default for the
      `min_confidence` argument of `Library.add_abstract` (and the
      `--min-confidence` option of the `add_abstract` CLI command) --
      one of `"high"`, `"medium"`, or `"low"`.
    * `mark_empty` (default `False`): the default for the `mark_empty`
      argument (`--mark-empty/--no-mark-empty`).
    """

    def __init__(self):
        self._min_confidence = "high"
        self.mark_empty = False

    @property
    def min_confidence(self):
        """The default confidence threshold (see the class
        docstring)."""
        return self._min_confidence

    @min_confidence.setter
    def min_confidence(self, value):
        if value not in ("high", "medium", "low"):
            raise ValueError(
                "add_abstract min_confidence must be one of 'high', "
                f"'medium', 'low', not {value!r}"
            )
        self._min_confidence = value

    def __repr__(self):
        return (
            f"AddAbstract(min_confidence={self._min_confidence!r}, "
            f"mark_empty={self.mark_empty!r})"
        )


def _parse_add_abstract(raw):
    """Read the optional `[add_abstract]` table from `raw`.

    Returns an {class}`AddAbstract` (holding the built-in defaults if
    the table is absent). `min_confidence` is validated by
    `AddAbstract`'s own setter."""
    settings = AddAbstract()
    table = raw.get("add_abstract", None)
    if table is None:
        return settings
    if not isinstance(table, dict):
        raise ValueError("[add_abstract] must be a table")
    unknown = set(table) - {"min_confidence", "mark_empty"}
    if unknown:
        warnings.warn(
            f"unknown key(s) in [add_abstract]: {sorted(unknown)}",
            UserWarning,
            stacklevel=5,
        )
    settings.min_confidence = table.get("min_confidence", "high")
    mark_empty = table.get("mark_empty", False)
    if not isinstance(mark_empty, bool):
        raise ValueError(
            "[add_abstract] mark_empty must be a boolean, "
            f"not {type(mark_empty)!r}"
        )
    settings.mark_empty = mark_empty
    return settings


def _parse_bool_table(raw, name, settings, defaults):
    """Read the optional boolean-valued table `name` from `raw` into
    the freshly constructed `settings` object, whose recognized keys
    (and their built-in defaults) are given by `defaults`. Returns
    `settings`."""
    table = raw.get(name, None)
    if table is None:
        return settings
    if not isinstance(table, dict):
        raise ValueError(f"[{name}] must be a table")
    unknown = set(table) - set(defaults)
    if unknown:
        warnings.warn(
            f"unknown key(s) in [{name}]: {sorted(unknown)}",
            UserWarning,
            stacklevel=5,
        )
    for key, default in defaults.items():
        value = table.get(key, default)
        if not isinstance(value, bool):
            raise ValueError(
                f"[{name}] {key} must be a boolean, not {type(value)!r}"
            )
        setattr(settings, key, value)
    return settings


class AddPreprint:
    """The `[add_preprint]` settings -- the defaults for the keyword
    arguments of {meth}`~bibdeskparser.Library.add_preprint` --
    exposed as `Library.config.add_preprint`.

    Attributes: `mark_empty` (default `False`), the default for the
    `mark_empty` argument of `Library.add_preprint` (and the
    `--mark-empty/--no-mark-empty` option of the `add_preprint` CLI
    command).
    """

    def __init__(self):
        self.mark_empty = False

    def __repr__(self):
        return f"AddPreprint(mark_empty={self.mark_empty!r})"


def _parse_add_preprint(raw):
    """Read the optional `[add_preprint]` table from `raw`.

    Returns an {class}`AddPreprint` (holding the built-in defaults if
    the table is absent)."""
    return _parse_bool_table(
        raw, "add_preprint", AddPreprint(), {"mark_empty": False}
    )


def _parse_initials(raw):
    """Read the optional `[initials]` table from `raw`.

    Returns a `dict` mapping a (lowercased) field name to a `dict`
    that maps a full field value (or `@string` macro name) to the
    initials the `%c` format specifier should produce for it."""
    table = raw.get("initials", {})
    if not isinstance(table, dict):
        raise ValueError("[initials] must be a table")
    initials = {}
    for field, mapping in table.items():
        if not isinstance(mapping, dict) or not all(
            isinstance(key, str) and isinstance(value, str)
            for key, value in mapping.items()
        ):
            raise ValueError(
                f"[initials.{field}] must be a table mapping field "
                "values to strings"
            )
        initials[field.lower()] = dict(mapping)
    return initials


def _parse_journal_macros(raw):
    """Read the optional `[journal_macros]` table from `raw`.

    The table maps an `@string` macro name to the full journal name it
    stands for, or to a list of names (the first being the canonical
    value of the macro, the rest aliases that resolve to the same
    macro on import). Returns a `dict` mapping the normalized
    (lowercased) macro name to a tuple of names."""
    table = raw.get("journal_macros", {})
    if not isinstance(table, dict):
        raise ValueError("[journal_macros] must be a table")
    journal_macros = {}
    for name, value in table.items():
        if not is_valid_macro_name(name, normalized=False):
            raise ValueError(
                f"[journal_macros] contains an invalid macro name: {name!r}"
            )
        names = [value] if isinstance(value, str) else value
        if (
            not isinstance(names, list)
            or not names
            or not all(
                isinstance(journal, str) and journal.strip()
                for journal in names
            )
        ):
            raise ValueError(
                f"[journal_macros] {name} must be a journal name or a "
                "non-empty list of journal names"
            )
        normalized = normalize_macro_name(name)
        if normalized in journal_macros:
            raise ValueError(
                f"[journal_macros] defines macro {normalized!r} more "
                "than once"
            )
        journal_macros[normalized] = tuple(
            journal.strip() for journal in names
        )
    return journal_macros


def _parse_protected_words(raw):
    """Read the optional `protected_words` key from `raw`.

    Returns a list of words (or phrases) that
    {meth}`~bibdeskparser.Library.import_bibtex` always wraps in
    braces inside a `title` to protect their capitalization."""
    value = raw.get("protected_words", [])
    if not isinstance(value, list) or not all(
        isinstance(word, str) and word.strip() for word in value
    ):
        raise ValueError("protected_words must be a list of non-empty strings")
    return [word.strip() for word in value]


# -- the active configuration ----------------------------------------- #


class Config:
    """The process-global configuration, publicly exposed as the
    `Library.config` class attribute (and thus also readable from any
    library instance, `bib.config`).

    The single instance of this class is {data}`active`; {meth}`load`
    and {meth}`reset` mutate it in place, so every reference to it stays
    current. Attributes may be assigned directly for an in-process
    override; assignment never writes back to the configuration file,
    and (re)loading a configuration replaces any override.

    Attributes (see the [configuration](configuration) reference page
    for their meaning and TOML spelling):

    * `verify_types` (default `True`): whether an unrecognized entry
      type is rejected with a `ValueError`.
    * `verify_fields` (default `True`): whether assigning a field
      inappropriate for an entry's type emits a `UserWarning`.
    * `config_file` (default `None`): an explicit `bibdeskparser.toml`
      path that takes precedence over directory-based discovery.
    * `default_bib_file` (default `None`): the `.bib` file the
      command-line interface operates on when none is given.
    * `auto_key` (an {class}`AutoKey`): the `[auto_key]` settings for
      autogenerated citation keys -- `auto_key.format_spec` (the format
      for {meth}`~bibdeskparser.Library.rekey`), `auto_key.lowercase`,
      and `auto_key.clean`.
    * `auto_file` (an {class}`AutoFile`): the `[auto_file]` settings
      for autogenerated attachment file names (used by
      {meth}`~bibdeskparser.Library.add_file` and
      {meth}`~bibdeskparser.Library.rename_file`) --
      `auto_file.format_spec`, `auto_file.location`,
      `auto_file.lowercase`, `auto_file.clean`, and
      `auto_file.file_automatically`.
    * `add_abstract` (an {class}`AddAbstract`): the `[add_abstract]`
      defaults for the keyword arguments of
      {meth}`~bibdeskparser.Library.add_abstract` --
      `add_abstract.min_confidence` (default `"high"`) and
      `add_abstract.mark_empty` (default `False`).
    * `add_preprint` (an {class}`AddPreprint`): the `[add_preprint]`
      defaults for the keyword arguments of
      {meth}`~bibdeskparser.Library.add_preprint` --
      `add_preprint.mark_empty` (default `False`).
    * `initials` (default `{}`): per-field acronym exceptions for the
      `%c` format specifier.
    * `journal_macros` (default `{}`): journal-name-to-macro mappings
      used by {meth}`~bibdeskparser.Library.import_bibtex` (and thus
      {meth}`~bibdeskparser.Library.add`) to resolve a journal name to
      an `@string` macro -- a `dict` mapping a macro name to a tuple
      of journal names (the first being the canonical value of the
      macro, the rest aliases).
    * `protected_words` (default `[]`): words (or phrases) that
      {meth}`~bibdeskparser.Library.import_bibtex` always wraps in
      braces inside a `title` to protect their capitalization.

    The remaining attributes hold the effective entry-type/field data
    model -- the built-in tables from `bibdeskparser.entrytypes`,
    possibly extended or replaced by a config file: `documented_types`,
    `recognized_entry_types`, `universal_fields`, `known_fields`, and
    the derived `type_fields` (the per-type union of required and
    optional fields, recomputed from `documented_types` on load).
    """

    # `reset` (not `__init__` directly) assigns all instance
    # attributes, so that `__init__` and a later `reset()` call share
    # the same logic.
    # pylint: disable=attribute-defined-outside-init

    def __init__(self):
        self.reset()

    def reset(self):
        """Reset all configuration to the built-in defaults, including
        the `config_file` override. Mainly useful for tests."""
        self.config_file = None
        self._apply_defaults()

    def _apply_defaults(self):
        """Reset every *loadable* setting (everything except the
        `config_file` override) to the built-in defaults."""
        self.verify_types = True
        self.verify_fields = True
        self.default_bib_file = None
        self.auto_key = AutoKey()
        self.auto_file = AutoFile()
        self.add_abstract = AddAbstract()
        self.add_preprint = AddPreprint()
        self.initials = {}
        self.journal_macros = {}
        self.protected_words = []
        self.documented_types = {
            entry_type: {
                "required": tuple(spec["required"]),
                "optional": tuple(spec["optional"]),
            }
            for entry_type, spec in entrytypes.DOCUMENTED_TYPES.items()
        }
        self.recognized_entry_types = set(entrytypes.RECOGNIZED_ENTRY_TYPES)
        self.universal_fields = set(entrytypes.UNIVERSAL_FIELDS)
        self.known_fields = set(entrytypes.KNOWN_FIELDS)
        self._recompute()

    def _recompute(self):
        """Derive `type_fields` from `documented_types`."""
        self.type_fields = {
            entry_type: frozenset(spec["required"])
            | frozenset(spec["optional"])
            for entry_type, spec in self.documented_types.items()
        }

    def load(self, bib_dir=None):
        """Discover and apply a `bibdeskparser.toml`.

        Searches (see {func}`discover`, honoring the `config_file`
        override) and, if a file is found, parses it and applies it in
        place; otherwise resets every loadable setting to the built-in
        defaults (`config_file` itself is kept). Returns the `Path`
        that was applied, or `None` if none was found.

        Raises {exc}`ValueError` if the discovered file is malformed
        (in which case the configuration is left unchanged), and
        {exc}`FileNotFoundError` if an explicit `config_file` does not
        exist.
        """
        path = discover(bib_dir=bib_dir, config_file=self.config_file)
        if path is None:
            self._apply_defaults()
            return None
        # Parse and validate everything *before* mutating any attribute,
        # so a malformed file leaves the configuration unchanged.
        raw = _parse(path)
        default_bib_file = _parse_default_bib_file(raw)
        auto_key = _parse_auto_key(raw)
        auto_file = _parse_auto_file(raw)
        add_abstract = _parse_add_abstract(raw)
        add_preprint = _parse_add_preprint(raw)
        initials = _parse_initials(raw)
        journal_macros = _parse_journal_macros(raw)
        protected_words = _parse_protected_words(raw)
        tables = _build(raw)
        self.verify_types = tables["verify_types"]
        self.verify_fields = tables["verify_fields"]
        self.documented_types = tables["documented_types"]
        self.recognized_entry_types = tables["recognized_entry_types"]
        self.universal_fields = tables["universal_fields"]
        self.known_fields = tables["known_fields"]
        self._recompute()
        self.default_bib_file = default_bib_file
        self.auto_key = auto_key
        self.auto_file = auto_file
        self.add_abstract = add_abstract
        self.add_preprint = add_preprint
        self.initials = initials
        self.journal_macros = journal_macros
        self.protected_words = protected_words
        return path

    # -- validation against the active data model --------------------- #

    def normalize_entry_type(self, value):
        """Return the normalized (lowercased) form of an entry type.

        `value` (a `str`) is lowercased and validated against the
        recognized entry types (the types BibDesk templates plus the
        extended data-model types, as configured). If entry-type
        validation is disabled (`verify_types`), any lowercased value
        is accepted.

        Raises {exc}`TypeError` if `value` is not a `str`, and
        {exc}`ValueError` if it is not a recognized entry type.

        ```python
        >>> from bibdeskparser.config import active
        >>> active.normalize_entry_type("Article")
        'article'
        >>> active.normalize_entry_type("bogus")
        Traceback (most recent call last):
            ...
        ValueError: invalid entry type: 'bogus'

        ```
        """
        if not isinstance(value, str):
            raise TypeError(f"entry type must be a str, not {type(value)!r}")
        lowered = value.lower()
        if not self.verify_types:
            return lowered
        if lowered in self.recognized_entry_types:
            return lowered
        raise ValueError(f"invalid entry type: {value!r}")

    def is_known_field(self, key):
        """Return whether `key` is a recognized field name.

        `key` is compared case-insensitively against the recognized
        field names (the classic BibTeX/BibDesk fields together with
        the extended data-model fields, plus any added through the
        configuration file).

        ```python
        >>> from bibdeskparser.config import active
        >>> active.is_known_field("Title")
        True
        >>> active.is_known_field("nonsense")
        False

        ```
        """
        return key.lower() in self.known_fields

    def field_is_appropriate(self, entry_type, key):
        """Return whether `key` is an appropriate field for
        `entry_type`.

        Both arguments are compared case-insensitively. If field
        validation is disabled (`verify_fields`), every field is
        treated as appropriate. Otherwise a field is appropriate if it
        is a universal field (accepted on any type), or -- for a type
        BibDesk templates -- one of that type's required/optional
        fields. For a recognized type that BibDesk does not template,
        any recognized field is appropriate.

        ```python
        >>> from bibdeskparser.config import active
        >>> active.field_is_appropriate("article", "Journal")
        True
        >>> active.field_is_appropriate("article", "publisher")
        False
        >>> active.field_is_appropriate("book", "keywords")  # universal
        True

        ```
        """
        if not self.verify_fields:
            return True
        lkey = key.lower()
        if lkey in self.universal_fields:
            return True
        allowed = self.type_fields.get(entry_type.lower())
        if allowed is not None:
            return lkey in allowed
        return self.is_known_field(lkey)


#: The single, process-global `Config` instance; `Library.config` is
#: this object.
active = Config()
