"""BibDesk's format-specifier language.

This module is a Python translation of the parts of BibDesk's
`BDSKFormatParser` (and its supporting string utilities) that turn a
format string like `"%a1%c{journal}0%Y%u0"` into a generated string
for an {class}`~bibdeskparser.Entry`: {func}`compile_format` parses and
validates a format, and {func}`render_format` renders it. See the
[format specifiers](format-specifiers) reference page for the language
itself.

BibDesk uses this one language for both its autogenerated citation keys
and its AutoFile feature (autogenerated attachment file names).
`bibdeskparser` currently wires it up to citation-key generation only,
so the specifiers that exist solely for file names (`%l`, `%L`, `%e`,
`%E`) are rejected, exactly as BibDesk's own format validation rejects
them outside the file-name context.

.. TODO: Support the AutoFile (local-file) context, which additionally
   needs the `%l`/`%L`/`%e`/`%E` specifiers, `/` as a directory
   separator, and the "papers folder" resolution.
"""

import calendar
import dataclasses
import random
import re
import unicodedata
import urllib.parse
import zlib

from .macros import MacroString

__all__ = []

# All members whose name does not start with an underscore must be listed
# either in __all__ or in __private__
__private__ = [
    "compile_format",
    "render_format",
    "required_fields",
    "missing_required_fields",
]


# Shared random source for the %r/%R/%d specifiers (seedable in tests).
_RNG = random.Random()

# The set of valid specifier characters (BDSKFormatParser
# `validSpecifierChars`).
_VALID_SPECIFIERS = frozenset("aApPtTmyYlLeEbkfwcsirRduUn0123456789%[]-")

# Specifier characters that are escapes for a literal character.
_ESCAPE_SPECIFIERS = frozenset("0123456789%[]-")

# Specifiers only valid when generating local file names (AutoFile).
_LOCAL_FILE_SPECIFIERS = frozenset("lLeE")

# Unique specifiers (at most one may occur in a format).
_UNIQUE_SPECIFIERS = frozenset("uUn")

# Specifiers with a compulsory `{Field}` argument.
_ARG_SPECIFIERS = frozenset("fwcsi")

# The number of optional `[...]` arguments each specifier accepts.
_NUM_OPT_ARGS = {
    "a": 2,  # [separator][etal]
    "p": 2,
    "A": 3,  # [author separator][name separator][etal]
    "P": 3,
    "T": 1,  # [small word length]
    "E": 1,  # [default extension]
    "k": 2,  # [slash][separator]
    "f": 1,  # [slash]
    "w": 3,  # [separator chars][slash][separator]
    "s": 3,  # [yes][no][mixed]
    "u": 2,  # [prefix][suffix] (count 0) / [field to hash] (count > 0)
    "U": 2,
    "n": 2,
}

# Characters that may appear in a *hand-entered* cite key: printable
# ASCII except the characters BibTeX/TeX cannot digest (BDSKTypeManager
# `invalidCiteKeyCharSet`, inverted). Used to sanitize literal text.
_VALID_KEY_CHARS = frozenset(
    chr(c) for c in range(32, 126) if chr(c) not in " '\"@,\\#}{~%()="
)

# Characters allowed in a *generated* cite key (BDSKTypeManager
# `strictInvalidCiteKeyCharSet`, inverted): very strict.
_STRICT_VALID_KEY_CHARS = frozenset(
    "abcdefghijklmnopqrstuvwxyz"
    + "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    + "-./0123456789:;"
)

# Replacements for composed/ligature characters that decomposition does
# not split (from BibDesk's `__BDReplaceComposedCharacters`; obvious
# typos in that table -- 0x0198 for 0x00C6, "it" for "st", and the
# swapped 0x0140/0x0141 -- are corrected here).
_COMPOSED_MAP = {
    0x0132: "IJ",
    0x0133: "ij",
    0x00C6: "AE",
    0x00E6: "ae",
    0x0152: "OE",
    0x0153: "oe",
    0xA74E: "OO",
    0xA74F: "oo",
    0xA732: "AA",
    0xA733: "aa",
    0xA734: "AO",
    0xA735: "ao",
    0xA736: "AU",
    0xA737: "au",
    0xA738: "AV",
    0xA739: "av",
    0xA73A: "AV",
    0xA73B: "av",
    0xA73C: "AY",
    0xA73D: "ay",
    0xA728: "TZ",
    0xA729: "tz",
    0xA760: "VY",
    0xA761: "vy",
    0x1D6B: "ue",
    0xFB00: "ff",
    0xFB01: "fi",
    0xFB02: "fl",
    0xFB03: "ffi",
    0xFB04: "ffl",
    0x1E9E: "SS",
    0x00DF: "ss",
    0xFB05: "st",
    0xFB06: "st",
    0x00D8: "O",
    0x00F8: "o",
    0x0110: "D",
    0x0111: "d",
    0x0126: "H",
    0x0127: "h",
    0x0140: "l",
    0x0141: "L",
    0x0166: "T",
    0x0167: "t",
    0x00D0: "D",
    0x00F0: "d",
    0x00DE: "TH",
    0x00FE: "th",
}

# A TeX command that "wraps" text, e.g. `\emph` in `\emph{word}`: a
# backslash followed by letters (or a single non-letter character),
# immediately followed by `{` and a non-`}` character. Matches
# BibDesk's `BDRangeOfTeXCommand`; `\LaTeX{}` is deliberately not
# matched (empty braces), so such commands survive.
_TEX_COMMAND_RX = re.compile(r"\\(?:[A-Za-z]+|[^A-Za-z])(?=\{[^}])")

# An unescaped curly brace (previous character is not a backslash).
_UNESCAPED_BRACE_RX = re.compile(r"(?<!\\)[{}]")

# BibDesk's virtual "Container" field (`BibItem.container`): the field
# naming a publication's venue, which differs by entry type. Types not
# listed have no container (the virtual field is empty for them).
#
# Accepting `container` as a `{Field}` name in a format (so a single
# format like `%a1%c{container}0%Y%u0` keys a mixed-type library) is a
# bibdeskparser feature that BibDesk's own format language does not
# have. It is intentionally left out of the user-facing docs: the
# documented way to key a mixed library is a per-type `format_spec`.
# The feature is supported and tested (see tests/test_specifiers.py),
# just deliberately undocumented -- do not add it to the docs.
_CONTAINER_FIELDS = {
    "article": "journal",
    "inproceedings": "booktitle",
    "conference": "booktitle",
    "incollection": "booktitle",
    "inbook": "title",
    "book": "series",
    "commented": "volumetitle",
}

_ENGLISH_MONTHS = {
    name.lower(): number
    for number, name in enumerate(calendar.month_name)
    if name
}
_ENGLISH_MONTHS.update(
    {
        name.lower(): number
        for number, name in enumerate(calendar.month_abbr)
        if name
    }
)


@dataclasses.dataclass
class _Literal:
    """A literal-text token of a compiled format."""

    text: str


@dataclasses.dataclass
class _Spec:
    """A `%`-specifier token of a compiled format.

    `args` holds the optional `[...]` arguments (`None` where an
    argument was not given -- as opposed to given-but-empty `[]`);
    `arg_escaped` records whether the last given argument ended in an
    escaped character (which suppresses the "etal digit" rule)."""

    char: str
    field: str = None
    args: tuple = ()
    arg_escaped: bool = False
    names: int = None
    from_end: bool = False
    number: int = None


@dataclasses.dataclass
class _Format:
    """A compiled format: the original string plus its token list."""

    text: str
    tokens: list


class _Scanner:
    """A minimal cursor-based string scanner (mirrors `NSScanner`
    usage in `BDSKFormatParser`)."""

    def __init__(self, string):
        self.string = string
        self.pos = 0

    def at_end(self):
        return self.pos >= len(self.string)

    def next_char(self):
        char = self.string[self.pos]
        self.pos += 1
        return char

    def scan_string(self, literal):
        if self.string.startswith(literal, self.pos):
            self.pos += len(literal)
            return True
        return False

    def scan_up_to(self, chars):
        """Consume and return text up to (excluding) any of `chars`,
        or up to the end; returns `""` if already at a stop char."""
        start = self.pos
        while self.pos < len(self.string) and (
            self.string[self.pos] not in chars
        ):
            self.pos += 1
        return self.string[start : self.pos]

    def scan_uint(self):
        """Consume a run of digits; return `int` or `None`."""
        start = self.pos
        while self.pos < len(self.string) and self.string[self.pos].isdigit():
            self.pos += 1
        if self.pos == start:
            return None
        return int(self.string[start : self.pos])

    def scan_signed_digit(self):
        """Consume a single digit with optional `-` sign; return
        `(digit, negative)` or `(None, False)`."""
        pos = self.pos
        negative = False
        if not self.at_end() and self.string[self.pos] == "-":
            self.pos += 1
            negative = True
        if not self.at_end() and self.string[self.pos].isdigit():
            digit = int(self.string[self.pos])
            self.pos += 1
            return digit, negative
        self.pos = pos
        return None, False


def _scan_opt_arg(scanner):
    """Scan an optional `[...]` argument at the current position.

    Returns `(value, last_char_escaped)`, with `value = None` if there
    is no `[` at the current position. Inside the brackets, `%x`
    escapes a literal character `x` (validated like a format escape).
    Raises {exc}`ValueError` on an invalid escape or a missing `]`."""
    if not scanner.scan_string("["):
        return None, False
    parts = []
    escaped = False
    while True:
        chunk = scanner.scan_up_to("%]")
        if chunk:
            parts.append(chunk)
            escaped = False
        if not scanner.scan_string("%"):
            break
        if scanner.at_end():
            raise ValueError("empty specifier '%' at end of format")
        char = scanner.next_char()
        _check_escape(char)
        parts.append(char)
        escaped = True
    if not scanner.scan_string("]"):
        raise ValueError("missing ']' after '[' in format")
    return "".join(parts), escaped


def _check_escape(char):
    """Validate `char` as an escape specifier (`%<char>`) in a
    format string, raising {exc}`ValueError` if invalid."""
    if char not in _ESCAPE_SPECIFIERS:
        raise ValueError(f"invalid specifier %{char} in format")
    if char not in _VALID_KEY_CHARS:
        # e.g. `%%`: `%` cannot occur in a generated key
        raise ValueError(f"invalid escape specifier %{char} in format")


def _normalize_field(name):
    """Normalize a `{Field}` argument to the lowercase field name used
    by {class}`~bibdeskparser.Entry`, with BibDesk's special names
    (`Cite Key` and its variants, `BibTeX Type`) mapped to canonical
    spellings."""
    name = name.strip().lower()
    if name in ("cite key", "cite-key", "citekey"):
        return "cite key"
    if name == "bibtex type":
        return "bibtex type"
    return name


def _container_field(entry):
    """The concrete field the virtual `container` field resolves to for
    `entry`'s type (BibDesk's `BibItem.container`), or `None` if the
    entry type has no container (e.g. `@misc`, `@unpublished`)."""
    return _CONTAINER_FIELDS.get(entry.entry_type)


def _resolve_field(entry, field):
    """Resolve the virtual `container` field name to the concrete field
    for `entry`'s type; every other name passes through unchanged.
    Returns `None` if `field` is `container` but the entry type has no
    container field."""
    if field == "container":
        return _container_field(entry)
    return field


def compile_format(format_string):
    """Parse and validate a format string.

    Returns an opaque compiled form for {func}`render_format` /
    {func}`required_fields`. Raises {exc}`ValueError` for a malformed
    format (unknown or misused specifiers, missing `{Field}` argument,
    a second unique specifier, specifiers that are only valid for
    local-file formats), and {exc}`NotImplementedError` for the `%i`
    (document info) specifier."""
    scanner = _Scanner(format_string)
    tokens = []
    found_unique = False
    while not scanner.at_end():
        literal = scanner.scan_up_to("%")
        if literal:
            tokens.append(_Literal(_sanitize(literal)))
        if not scanner.scan_string("%"):
            break
        if scanner.at_end():
            raise ValueError("empty specifier '%' at end of format")
        char = scanner.next_char()
        if char not in _VALID_SPECIFIERS:
            raise ValueError(f"invalid specifier %{char} in format")
        if char in _ESCAPE_SPECIFIERS:
            _check_escape(char)
            tokens.append(_Literal(char))
            continue
        if char in _LOCAL_FILE_SPECIFIERS:
            raise ValueError(
                f"specifier %{char} is only valid in a format for "
                "local files (BibDesk's AutoFile feature), not for "
                "citation keys"
            )
        if char == "i":
            # TODO: implement %i once bibdeskparser models BibDesk's
            # document info (the `@bibdesk_info{document_info, ...}`
            # block that BibDesk saves into the .bib file).
            raise NotImplementedError(
                "the %i specifier (BibDesk document info) is not "
                "implemented"
            )
        if char in _UNIQUE_SPECIFIERS:
            if found_unique:
                raise ValueError(
                    f"unique specifier %{char} can appear only once "
                    "in format"
                )
            found_unique = True
        spec = _Spec(char)
        if char in _ARG_SPECIFIERS:
            if (
                scanner.at_end()
                or not scanner.scan_string("{")
                or not (field := scanner.scan_up_to("}"))
                or not scanner.scan_string("}")
            ):
                raise ValueError(
                    f"specifier %{char} must be followed by a {{Field}} name"
                )
            spec.field = _normalize_field(field)
        num_opt_args = _NUM_OPT_ARGS.get(char, 0)
        args = []
        arg_escaped = False
        for _ in range(num_opt_args):
            value, escaped = _scan_opt_arg(scanner)
            if value is None:
                break
            args.append(value)
            arg_escaped = escaped
        spec.args = tuple(args) + (None,) * (num_opt_args - len(args))
        spec.arg_escaped = arg_escaped
        if char in "aApP":
            spec.names, spec.from_end = scanner.scan_signed_digit()
        if char in "aptTkfwcsrRduUn":
            spec.number = scanner.scan_uint()
        tokens.append(spec)
    return _Format(text=format_string, tokens=tokens)


def required_fields(fmt):
    """The fields a format needs, as a `list` of requirement names.

    Mirrors BibDesk's `requiredFieldsForFormat:`: `"author"` for
    `%a`/`%A`, `"author/editor"` for `%p`/`%P` (either field
    satisfies it), `"title"`, `"year"`, `"month"`, `"keywords"`, and
    the `{Field}` argument of `%f`/`%w`/`%c`. The always-available
    pseudo-fields (`cite key`, `bibtex type`) are not included; the
    virtual `container` field *is* (its per-type requirement is
    resolved by {func}`missing_required_fields`)."""
    fields = []
    for token in fmt.tokens:
        if not isinstance(token, _Spec):
            continue
        if token.char in "aA":
            fields.append("author")
        elif token.char in "pP":
            fields.append("author/editor")
        elif token.char in "tT":
            fields.append("title")
        elif token.char in "yY":
            fields.append("year")
        elif token.char == "m":
            fields.append("month")
        elif token.char == "k":
            fields.append("keywords")
        elif token.char in "fwc":
            if token.field not in ("cite key", "bibtex type"):
                fields.append(token.field)
    # Dedupe while preserving first-seen order: a format may reference
    # the same requirement more than once (e.g. `%a%a`).
    return list(dict.fromkeys(fields))


def missing_required_fields(fmt, entry):
    """The subset of {func}`required_fields` that `entry` does not
    provide (a `list`, empty if the format can be fully rendered)."""
    missing = []
    for field in required_fields(fmt):
        if field == "author/editor":
            if not (entry.get("author") or entry.get("editor")):
                missing.append(field)
        elif field == "container":
            # `container` resolves to a per-type field (journal for an
            # article, booktitle for inproceedings, ...); it is required
            # only when the entry type *has* a container field, so a
            # single format stays usable across all entry types.
            concrete = _container_field(entry)
            if concrete is not None and not entry.get(concrete):
                missing.append(field)
        elif not entry.get(field):
            missing.append(field)
    return missing


# -- sanitization ------------------------------------------------------ #


def _replace_composed(string):
    """Decompose accented characters and drop the combining marks,
    then replace the remaining ligatures/special letters (BibDesk's
    `stringByReplacingComposedCharacters`)."""
    decomposed = unicodedata.normalize("NFD", string)
    stripped = "".join(
        char for char in decomposed if not unicodedata.combining(char)
    )
    return stripped.translate(_COMPOSED_MAP)


def _remove_braces(string):
    """Remove unescaped curly braces and unescape `\\{`/`\\}`
    (BibDesk's `stringByRemovingCurlyBraces`)."""
    string = _UNESCAPED_BRACE_RX.sub("", string)
    return string.replace(r"\{", "{").replace(r"\}", "}")


def _remove_tex(string):
    """Remove TeX commands that wrap text (e.g. `\\emph{...}`) and all
    unescaped braces, then unescape `\\{ \\} \\& \\%` (BibDesk's
    `stringByRemovingTeX`)."""
    while True:
        new = _TEX_COMMAND_RX.sub("", string, count=1)
        if new == string:
            break
        string = new
    string = _UNESCAPED_BRACE_RX.sub("", string)
    for special in "{}&%":
        string = string.replace("\\" + special, special)
    return string


def _sanitize(string):
    """Sanitize literal format text for use in a generated key
    (BibDesk's non-strict `stringBySanitizingString:forField:`)."""
    string = _replace_composed(string)
    string = re.sub(r"\s", "-", string)
    return "".join(char for char in string if char in _VALID_KEY_CHARS)


def _strict_sanitize(string, clean="tex"):
    """Sanitize a field value for use in a generated key
    (BibDesk's `stringByStrictlySanitizingString:forField:`).

    `clean` is the TeX-cleaning level: `"none"`, `"braces"` (remove
    curly braces), or `"tex"` (also remove TeX commands; the
    default, matching BibDesk's default preference)."""
    if not string:
        return ""
    if clean == "braces":
        string = _remove_braces(string)
    elif clean == "tex":
        string = _remove_tex(string)
    string = _replace_composed(string)
    string = re.sub(r"\s", "-", string)
    string = string.encode("ascii", "ignore").decode("ascii")
    return "".join(char for char in string if char in _STRICT_VALID_KEY_CHARS)


# -- field access ------------------------------------------------------ #


def _raw_value(entry, field, current_key):
    """The decoded value of `field`, *without* macro expansion (a
    `str`, possibly a {class}`~bibdeskparser.MacroString`; `""` if the
    field is missing)."""
    if field == "cite key":
        return current_key or ""
    if field == "bibtex type":
        return entry.entry_type
    field = _resolve_field(entry, field)
    if field is None:
        return ""
    try:
        value = entry[field]
    except KeyError:
        return ""
    return value if isinstance(value, str) else str(value)


def _field_value(entry, field, strings, current_key):
    """The string value of `field` for `entry`, with a bare `@string`
    macro reference expanded via `strings` (an undefined macro falls
    back to the macro name itself)."""
    value = _raw_value(entry, field, current_key)
    if isinstance(value, MacroString) and strings:
        return strings.get(str(value), str(value))
    return str(value)


def _int_prefix(string):
    """The integer prefix of `string` (like `NSString integerValue`):
    optional sign and leading digits, `0` if there are none."""
    match = re.match(r"\s*([+-]?\d+)", string)
    return int(match.group(1)) if match else 0


def _year_number(value):
    """The year encoded in a `year` field value (BibDesk's `NSDate
    yearFromString:`): its integer prefix, with a two-digit value
    mapped into 1950--2049."""
    year = _int_prefix(value)
    if len(value) == 2:
        year += 2000 if year < 50 else 1900
    return year


def _month_number(value):
    """The month number (1--12) encoded in a `month` field value
    (BibDesk's `NSDate monthFromString:`), or `0` if it cannot be
    parsed. Handles both English month names/abbreviations (e.g. the
    standard `jan` ... `dec` macros) and numeric values."""
    match = re.search(r"[^\W\d_]+", value)
    if match:
        token = match.group(0)
    else:
        token = ""
        digit_runs = re.findall(r"\d+", value)
        if digit_runs:
            token = digit_runs[0]
            if len(token) > 2 and len(digit_runs) > 1:
                # e.g. "2024-05": the first run is a year
                token = digit_runs[1]
    if not token:
        return 0
    if len(token) < 3 and token[0].isdigit():
        month = _int_prefix(token)
        return month if month <= 12 else 0
    return _ENGLISH_MONTHS.get(token.lower(), 0)


def _acronym(value, ignore_length):
    """The acronym of `value` (BibDesk's
    `acronymValueIgnoringWordLength:`): the uppercased first letter of
    every space-separated word longer than `ignore_length` characters
    (words ending in `.`, like `Phys.`, always count)."""
    result = []
    for component in value.split(" "):
        current_ignore = ignore_length
        component = component.strip()
        if len(component) > 1 and component.endswith("."):
            current_ignore = 0
        while component and not component[0].isalnum():
            component = component[1:]
        while component and not component[-1].isalnum():
            component = component[:-1]
        if len(component) > current_ignore:
            result.append(component[0].upper())
    return "".join(result)


def _split_words(string, sep_chars):
    """Split `string` on runs of the characters in `sep_chars`,
    dropping empty items (mirrors the word-scanning loops in
    `BDSKFormatParser`)."""
    if not any(char in string for char in sep_chars):
        return [string]
    pattern = "[" + re.escape(sep_chars) + "]+"
    return [word for word in re.split(pattern, string) if word]


def _bool_int(value):
    """The integer interpretation of a boolean/tri-state field value
    (BibDesk's `integerValueOfField:`): `1` for yes/true, `0` for
    no/false/empty, `-1` for a mixed tri-state value."""
    value = value.strip().lower()
    if value in ("yes", "y", "true", "1"):
        return 1
    if value in ("no", "n", "false", "0", ""):
        return 0
    if value in ("mixed", "-1"):
        return -1
    return 0


# -- specifier rendering ----------------------------------------------- #


class _Renderer:
    """Rendering state for one {func}`render_format` call."""

    def __init__(
        self,
        entry,
        *,
        strings=None,
        initials=None,
        clean="tex",
        current_key=None,
        document_name=None,
    ):
        self.entry = entry
        self.strings = strings or {}
        self.initials = initials or {}
        self.clean = clean
        self.current_key = current_key
        self.document_name = document_name

    def value(self, field):
        return _field_value(self.entry, field, self.strings, self.current_key)

    def sanitized(self, string):
        return _strict_sanitize(string, clean=self.clean)

    def render(self, spec):
        """Render one non-unique specifier token to a string."""
        return getattr(self, "_render_" + spec.char)(spec)

    # -- individual specifiers ---------------------------------------- #

    def _names(self, spec, with_editor):
        people = self.entry.author
        if not people and with_editor:
            people = self.entry.editor
        return people

    def _num_names(self, spec, people):
        """The number of names to render, and the effective "etal"
        suffix (whose trailing digit may reduce the count)."""
        etal_index = 1 if spec.char in "ap" else 2
        etal = spec.args[etal_index]
        if etal is None:
            etal = ""
        num = spec.names or 0
        if num == 0 or num > len(people):
            num = len(people)
        elif (
            num < len(people)
            and not spec.arg_escaped
            and etal
            and etal[-1].isdigit()
        ):
            digit = int(etal[-1])
            etal = etal[:-1]
            if 0 < digit < num:
                num = digit
        return num, etal

    def _render_a(self, spec):
        people = self._names(spec, with_editor=spec.char == "p")
        if not people:
            return ""
        sep = spec.args[0] if spec.args[0] is not None else ""
        num, etal = self._num_names(spec, people)
        num_chars = spec.number or 0
        parts = []
        for i in range(num):
            person = (
                people[len(people) - num + i] if spec.from_end else people[i]
            )
            name = self.sanitized(" ".join(person.last))
            if 0 < num_chars < len(name):
                name = name[:num_chars]
            parts.append(name)
        result = sep.join(parts)
        if num < len(people):
            result += etal
        return result

    _render_p = _render_a

    def _render_A(self, spec):
        people = self._names(spec, with_editor=spec.char == "P")
        if not people:
            return ""
        auth_sep = spec.args[0] if spec.args[0] is not None else ";"
        name_sep = spec.args[1] if spec.args[1] is not None else "."
        num, etal = self._num_names(spec, people)
        parts = []
        for i in range(num):
            person = (
                people[len(people) - num + i] if spec.from_end else people[i]
            )
            first = self.sanitized(" ".join(person.first))
            last = self.sanitized(" ".join(person.last))
            if first:
                parts.append(last + name_sep + first[0])
            else:
                parts.append(last)
        result = auth_sep.join(parts)
        if num < len(people):
            result += etal
        return result

    _render_P = _render_A

    def _render_t(self, spec):
        title = self.sanitized(self.value("title"))
        num_chars = spec.number or 0
        if 0 < num_chars < len(title):
            title = title[:num_chars]
        return title

    def _render_T(self, spec):
        title = self.value("title")
        if not title:
            return ""
        small_length = 3
        if spec.args[0] is not None:
            small_length = _int_prefix(spec.args[0])
        num_words = spec.number or 0
        words = title.split()
        if num_words == 0:
            num_words = len(words)
        parts = []
        for word in words:
            if num_words <= 0:
                break
            word = self.sanitized(word)
            if spec.args[0] is None or len(word) > small_length:
                if parts:
                    parts.append(self.sanitized(" "))
                parts.append(word)
                if len(word) > small_length:
                    num_words -= 1
        return "".join(parts)

    def _render_y(self, spec):
        value = self.value("year")
        if not value:
            return ""
        return f"{_year_number(value) % 100:02d}"

    def _render_Y(self, spec):
        value = self.value("year")
        if not value:
            return ""
        return str(_year_number(value))

    def _render_m(self, spec):
        value = _raw_value(self.entry, "month", self.current_key)
        if not value:
            return ""
        return f"{_month_number(str(value)) or 1:02d}"

    def _render_k(self, spec):
        slash = spec.args[0] if spec.args[0] is not None else "/"
        sep = spec.args[1] if spec.args[1] is not None else ""
        num_words = spec.number or 0
        keywords = self.entry.keywords
        parts = []
        for i, keyword in enumerate(keywords):
            if num_words and i >= num_words:
                break
            keyword = self.sanitized(keyword.strip())
            if slash != "/":
                keyword = keyword.replace("/", slash)
            if i > 0 and keyword and sep:
                parts.append(sep)
            parts.append(keyword)
        return "".join(parts)

    def _render_b(self, spec):
        if not self.document_name:
            return ""
        return _sanitize(self.document_name)

    def _render_f(self, spec):
        slash = spec.args[0] if spec.args[0] is not None else "/"
        num_chars = spec.number or 0
        value = self.value(spec.field)
        if not value:
            return ""
        value = self.sanitized(value)
        if slash != "/":
            value = value.replace("/", slash)
        if 0 < num_chars < len(value):
            value = value[:num_chars]
        return value

    def _render_w(self, spec):
        sep_chars = spec.args[0] if spec.args[0] else " "
        slash = spec.args[1] if spec.args[1] is not None else "/"
        sep = spec.args[2] if spec.args[2] is not None else ""
        num_words = spec.number or 0
        value = self.value(spec.field)
        if not value:
            return ""
        words = _split_words(value, sep_chars)
        parts = []
        for i, word in enumerate(words):
            if num_words and i >= num_words:
                break
            word = self.sanitized(word.strip())
            if slash != "/":
                word = word.replace("/", slash)
            if i > 0 and word and sep:
                parts.append(sep)
            parts.append(word)
        return "".join(parts)

    def _render_c(self, spec):
        value = self.value(spec.field)
        if not value:
            return ""
        # the [initials] table is keyed by the *concrete* field, so a
        # `%c{container}` looks up `[initials.journal]` for an article,
        # `[initials.booktitle]` for inproceedings, etc.
        field = _resolve_field(self.entry, spec.field) or spec.field
        mapped = self.initials.get(field, {}).get(value)
        if mapped is None:
            raw = _raw_value(self.entry, spec.field, self.current_key)
            if isinstance(raw, MacroString):
                mapped = self.initials.get(field, {}).get(str(raw))
        if mapped is not None:
            return self.sanitized(mapped)
        small_length = spec.number if spec.number is not None else 3
        return self.sanitized(_acronym(value, small_length))

    def _render_s(self, spec):
        yes = spec.args[0] if spec.args[0] is not None else ""
        no = spec.args[1] if spec.args[1] is not None else ""
        mixed = spec.args[2] if spec.args[2] is not None else ""
        num_chars = spec.number or 0
        int_value = _bool_int(self.value(spec.field))
        value = {0: no, 1: yes}.get(int_value, mixed)
        if 0 < num_chars < len(value):
            value = value[:num_chars]
        return value

    def _render_r(self, spec):
        count = spec.number if spec.number is not None else 1
        return "".join(
            chr(ord("a") + _RNG.randrange(26)) for _ in range(count)
        )

    def _render_R(self, spec):
        count = spec.number if spec.number is not None else 1
        return "".join(
            chr(ord("A") + _RNG.randrange(26)) for _ in range(count)
        )

    def _render_d(self, spec):
        count = spec.number if spec.number is not None else 1
        return "".join(str(_RNG.randrange(10)) for _ in range(count))


# -- uniqueness -------------------------------------------------------- #

_UNIQUE_CHARS = {
    "u": "abcdefghijklmnopqrstuvwxyz",
    "U": "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    "n": "0123456789",
}


def _hashed_field(entry, field, strings, current_key, universal):
    """The CRC-32 hash of a normalized field value, used to pick
    deterministic unique characters (BibDesk's `hashedField`); `None`
    if the field is empty. In `universal` mode, the hash is folded to
    reproduce the "universal cite key" of Papers 2/3."""
    if field == "doi":
        string = _field_value(entry, "doi", strings, current_key)
        is_url = "://" in string
        index = string.find("10.")
        if index < 0:
            return None
        string = string[index:]
        if is_url:
            string = urllib.parse.unquote(string)
    else:
        string = _field_value(entry, field, strings, current_key)
        if not string:
            return None
        string = _replace_composed(string.lower())
        string = re.sub(r"[_\-=/|.{}]", " ", string)
        string = re.sub(r"[^a-zA-Z0-9 ]", "", string)
        string = " ".join(string.split())
    if not string:
        return None
    crc = zlib.crc32(string.encode("utf-8"))
    if universal and field in ("title", "doi"):
        if field == "doi":
            crc = (crc % 26) + 26 * (1 + ((crc // 26) % 10))
        else:
            crc = (crc % 26) + 26 * (19 + ((crc // 26) % 4))
    return crc


def _current_matches(current, base, end, number, chars, prefix, suffix):
    """Whether the existing key `current` already fits the pattern
    `base + [prefix] + <unique chars> + [suffix] + end` (BibDesk's
    `currentString:matchesString:...`), so that regeneration keeps it
    instead of churning the unique suffix."""
    if not current or len(current) < len(base) + len(end):
        return False
    unique_length = len(current) - len(base) - len(end)
    if number > 0 and unique_length != number:
        return False
    if base and not current.startswith(base):
        return False
    if end and not current.endswith(end):
        return False
    if number == 0 and unique_length == 0:
        return True
    unique = current[len(base) : len(base) + unique_length]
    prefix = prefix or ""
    suffix = suffix or ""
    if prefix:
        if not unique.startswith(prefix):
            return False
        unique = unique[len(prefix) :]
    if suffix:
        if not unique.endswith(suffix):
            return False
        unique = unique[: unique_length - len(prefix) - len(suffix)]
    return all(char in chars for char in unique)


def _unique_string(base, end, number, chars, prefix, suffix, crc, is_valid):
    """Generate `base + <unique chars> + end` such that `is_valid`
    accepts it (BibDesk's `uniqueString:endingWith:...`).

    With `number == 0` the unique part grows only as needed (starting
    with none at all, then inserting `prefix`/`suffix` around it);
    with a fixed `number`, exactly that many characters are inserted,
    first deterministically from the `crc` hash if given. If no valid
    string exists, the final candidate is returned regardless."""
    fallback = ""
    if number == 0:
        candidate = base + end
        if is_valid(candidate):
            return candidate
        if prefix:
            base = base + prefix
        if suffix:
            end = suffix + end
    elif crc is not None:
        digits = []
        value = crc
        for _ in range(number):
            digits.append(chars[value % len(chars)])
            value //= len(chars)
        fallback = "".join(reversed(digits))
        candidate = base + fallback + end
        if is_valid(candidate):
            return candidate
    else:
        fallback = chars[-1] * number
    length = max(number, 1)
    while True:
        skip_zero = number == 0
        for combo in _combinations(chars, length, skip_zero=skip_zero):
            candidate = base + combo + end
            if is_valid(candidate):
                return candidate
        if number != 0:
            break
        length += 1
    return base + fallback + end


def _combinations(chars, length, skip_zero):
    """All strings of `length` characters from `chars`, in order; with
    `skip_zero`, combinations starting with `"0"` are skipped (a
    grown numeric suffix never starts with a zero)."""
    indices = [0] * length
    while True:
        combo = "".join(chars[i] for i in indices)
        if not (skip_zero and combo[0] == "0"):
            yield combo
        position = length - 1
        while position >= 0:
            indices[position] += 1
            if indices[position] < len(chars):
                break
            indices[position] = 0
            position -= 1
        if position < 0:
            return


def render_format(
    fmt,
    entry,
    *,
    strings=None,
    initials=None,
    lowercase=False,
    clean="tex",
    current_key=None,
    is_key_free=None,
    document_name=None,
):
    """Render a compiled format for an entry.

    # Arguments

    * `fmt`: the result of {func}`compile_format`.
    * `entry`: the {class}`~bibdeskparser.Entry` to render.
    * `strings`: a mapping of `@string` macro names to their values
      (e.g. `library.strings`), for expanding bare macro references.
    * `initials`: the `[initials]` mapping from the
      [configuration](configuration): field name to a `dict` mapping
      a full field value (or macro name) to the initials that `%c`
      should produce for it.
    * `lowercase`: lowercase the entire generated key (`%U` then adds
      lowercase characters, like `%u`).
    * `clean`: the TeX-cleaning level for field values (`"none"`,
      `"braces"`, or `"tex"`).
    * `current_key`: the entry's current citation key. If it already
      matches the pattern, it is returned unchanged (regenerating is
      idempotent); it also provides the `%f{Cite Key}` value.
    * `is_key_free`: a callable that decides whether a candidate key
      is available (i.e. not taken by *another* entry). `None` accepts
      every non-empty candidate.
    * `document_name`: the library file's name without extension (the
      `%b` value).

    Returns the generated key as a `str`.
    """
    renderer = _Renderer(
        entry,
        strings=strings,
        initials=initials,
        clean=clean,
        current_key=current_key,
        document_name=document_name,
    )
    base_parts = None
    parts = []
    unique_spec = None
    for token in fmt.tokens:
        if isinstance(token, _Literal):
            parts.append(token.text)
        elif token.char in _UNIQUE_SPECIFIERS:
            unique_spec = token
            base_parts = parts
            parts = []
        else:
            parts.append(renderer.render(token))
    if unique_spec is None:
        base, end = "".join(parts), ""
    else:
        base, end = "".join(base_parts), "".join(parts)

    unique_char = unique_spec.char if unique_spec else None
    number = 1
    prefix = suffix = None
    if unique_spec is not None:
        number = unique_spec.number if unique_spec.number is not None else 1
        prefix, suffix = unique_spec.args
        prefix = prefix or None
        suffix = suffix or None

    if lowercase:
        base = base.lower()
        end = end.lower()
        if unique_char == "U":
            unique_char = "u"

    # never return an empty key: fall back to a grown numeric suffix
    if not base and not end and unique_char is None:
        unique_char = "n"
        number = 0

    if unique_char is None:
        return base

    chars = _UNIQUE_CHARS[unique_char]

    def is_valid(candidate):
        if not candidate:
            return False
        return is_key_free is None or is_key_free(candidate)

    current = current_key if current_key and is_valid(current_key) else None
    if _current_matches(
        current,
        base,
        end,
        number,
        chars,
        prefix if number == 0 else None,
        suffix if number == 0 else None,
    ):
        return current

    crc = None
    if number > 0 and (prefix or suffix):
        # a [field] argument on the unique specifier names a field to
        # hash for deterministic unique characters
        universal = number == 2 and fmt.text.startswith("%a1:%Y%u[")
        hash_field = _normalize_field(prefix or suffix)
        crc = _hashed_field(entry, hash_field, strings, current_key, universal)
        if crc is None and prefix and suffix:
            crc = _hashed_field(
                entry,
                _normalize_field(suffix),
                strings,
                current_key,
                universal,
            )
        prefix = suffix = None

    return _unique_string(
        base, end, number, chars, prefix, suffix, crc, is_valid
    )
